const dummyData = [
    {
        carid: "C1",
        picture: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2Fyc3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80",
        modl: "Baleno",
        company : "Maruti-Suzuki",
        category : "Hatchback",
        rent : 7000,
        fuel_type : "Petrol",
        engine_type : "Manual",
        no_of_passengers : 5,
        plan : "per Day",
        penalty : 5000,
        features : ["Airbags", "Stereo", "Fog Lamp"],
        registration_no : 124235432131,
        lender_email: "manavkumar.v@ahduni.edu.in",
        lender_name : "Manavkumar Vagrecha",
        lender_add : "30/31, Hariyani Society, Opp. Neo Politian, Navsari, Gujarat, 396454",
        lender_phone : 8698567567,
        ref_deposit : 3145,
    },
    {
        carid: "C2",
	modl: "Seltos",
        company : "Kia",
        category : "SUV",
        rent : 10000,
        fuel_type : "Diesel",
        engine_type : "Automatic",
        no_of_passengers : 5,
        plan : "per Day",
        penalty : 5000,
        features : ["Airbags", "Stereo", "Fog Lamp"],
        registration_no : 321352462432,
        picture:"/car-demo/photo-1.webp",
        lender_email : "nightking007@gmail.com",
        lender_name : "Parth N. Patel",
        lender_add : "81-A, Surya Soc., b/d Club O7, Bopal, Ahmedabad, Gujarat, 380001",
        lender_phone : 1243564234,
        ref_deposit : 5124,
    },
    {
        carid: "C3",
	modl: "i20",
        company : "Hyundai",
        category : "Hatchback",
        rent : 5000,
        fuel_type : "Diesel",
        no_of_passengers : 5,
        plan : "per Day",
        engine_type : "Manual",
        penalty : 5000,
        features : ["Airbags", "Stereo", "Fog Lamp"],
        registration_no : 546732112446,
        picture: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1000&q=80",
        lender_email : "jeet.s3@ahduni.edu.in",
        lender_name : "Jeet D. Shah",
        lender_add : "41-C, Green Park Soc., Nr. Axis Bank, Surendranagar, Gujarat, 356786",
        lender_phone : 5426412434,
        ref_deposit : 2145,
    },{
        carid: "C4",
        picture: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/44879/landrover-discovery-sport-right-front-three-quarter16.jpeg?q=85",
        modl: "Baleno",
        company : "Maruti-Suzuki",
        category : "Hatchback",
        rent : 6000,
        fuel_type : "Petrol",
        engine_type : "Manual",
        no_of_passengers : 5,
        plan : "per Day",
        penalty : 5000,
        features : ["Airbags", "Stereo", "Fog Lamp"],
        registration_no : 124235432131,
        lender_email: "jeet.s3@ahduni.edu.in",
        lender_name : "Jeet D. Shah",
        lender_add : "30/31, Hariyani Society, Opp. Neo Politian, Navsari, Gujarat, 396454",
        lender_phone : 8698567567,
        ref_deposit : 3145,
    },
    {
        carid: "C5",
	modl: "Kia",
        company : "Seltos",
        category : "SUV",
        rent : 12000,
        fuel_type : "Diesel",
        engine_type : "Automatic",
        no_of_passengers : 5,
        plan : "per Day",
        penalty : 5000,
        features : ["Airbags", "Stereo", "Fog Lamp"],
        registration_no : 321352462432,
        picture:"https://images-ext-1.discordapp.net/external/wYtVtG_G4JNF-pRc_Cv2AAdW3XEYKfwpEatI7WnNFBE/https/www.extremetech.com/wp-content/uploads/2019/12/SONATA-hero-option1-764A5360-edit-768x425.jpg",
        lender_email : "shreyansh_shah@yahoo.com",
        lender_name : "Shreyansh N. Shah",
        lender_add : "81-A, Surya Soc., b/d Club O7, Bopal, Ahmedabad, Gujarat, 380001",
        lender_phone : 1243564234,
        ref_deposit : 5124,
    },
    {
	carid: "C6",
        modl: "XUV500",
        company : "Mahindra",
        category : "SUV",
        rent : 15000,
        fuel_type : "Diesel",
        no_of_passengers : 7,
        plan : "per Day",
        engine_type : "Manual",
        penalty : 5000,
        features : ["Airbags", "Stereo", "Fog Lamp"],
        registration_no : 546732112446,
        picture: "https://images-ext-2.discordapp.net/external/i1OasfnXYipctHw2RosbitA4n_SEn_z2hBw21xv6Mfg/https/static.autox.com/uploads/2019/03/Mahindra-XUV500-Exterior-Image-1-.jpg?width=789&height=484",
        lender_email : "shreyansh_shah@yahoo.com",
        lender_name : "Shreyansh N. Shah",
        lender_add : "41-C, Green Park Soc., Nr. Axis Bank, Surendranagar, Gujarat, 356786",
        lender_phone : 5426412434,
        ref_deposit : 2145,
    },
];

export default dummyData;